# Generated by Django 2.0 on 2017-12-20 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('A2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('important', models.BooleanField()),
            ],
        ),
    ]
