# Generated by Django 2.0 on 2017-12-21 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A2', '0005_task_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
